# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        orders:
            properties:
                id: { type: "integer" }
                userId: { type: "text" }
                address: { type: "text" }
                phoneNumber: { type: "text" }
                orderOption: { type: "text" }
                Status: { type: "text" }
                createdAt: { type: "date" }
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Orders
                provider: ~
                finder: ~